#!/bin/bash
choice=$1

if [ $choice = 1 ]; then
	printf "" > $HOME/.bash/running
	while true; do

	running="$(cat $HOME/.bash/running)"
  status="$(hyprctl activeworkspace | grep windows: | awk '{print $2}')"

		if [ "$status" -gt 0 ]; then
			if [ ! "$running" = 1 ]; then
				killall waybar
				printf 1 > $HOME/.bash/running
			fi
		fi
		
		if [ ! "$status" -gt 0 ]; then
			if [ ! "$running" = 0 ]; then
				killall waybar
				printf 0 > $HOME/.bash/running
				waybar -c $HOME/.config/waybar/leftbar/main.jsonc -s $HOME/.config/waybar/leftbar/main.css &
        sleep 0.05
				waybar -c $HOME/.config/waybar/border/config.jsonc -s $HOME/.config/waybar/border/style.css &
			fi
		fi
	done
else
	killall waybar
  killall refresh
  notify-send "Killed!" -u low --replace-id 9993 -t 1000
fi
